# COMMON
alias cls='clear && printf "\033[3J"'
alias gr='grep -i'
alias l='ls -lh --color'
alias la='ls -lha --color'
alias ll='ls -lhtr *.log --color'
alias lt='ls -lhtr --color'
alias nl='nslookup'
alias v='nvim'
alias p='ping'
alias py='python3'
alias ro='robot'
alias roa='robot -A'
alias t4='tail -n 60'
alias tf='tail -f'
# SPECIALS
alias brewup='~/git/scripts/brew/brewup.sh'
alias docls='~/git/scripts/docker_container_list.sh'
alias docim='docker images'
alias docip='docker image prune'
alias godo='cd ~/OneDrive\ -\ Deutsche\ Bahn/Documents/'
alias gons='cd ~/git/nso-services/'
alias goco='cd ~/.config'
alias gosc='cd ~/git/scripts'
alias gowa='cd ~/git/wan-access'
alias plum='java -jar /opt/homebrew/Cellar/plantuml/1.2025.3/libexec/plantuml.jar'
alias so='source ~/.venv/bin/activate'
# GIT
alias gaa='git add .'
alias gba='git branch --all'
alias gbd='git branch --delete'
alias gcb='git checkout -b'
alias gco='git checkout'
alias gcmsg='git commit -m' 
alias gd='git diff'
alias gf='git fetch'
alias gfa='git fetch --all --prune'
alias gl='git pull'
alias glg='git log --stat'
alias glgp='git log --stat -p'
alias glo='git log --oneline --decorate'
alias glol='git log  --pretty="-%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"'
alias glols='git log  --pretty="-%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --stat'
alias gp='git push'
alias grs='git restore'
alias grss='git restore --staged'
alias gst='git status --untracked-files'
# NSO native
alias cli='ncs_cli -Cu admin'
alias gol='cd ~/ncsrun/logs'
alias gop='cd ~/ncsrun/packages/'
alias ncss='ncs --cd ~/ncsrun'
alias ncsk='ncs --cd ~/ncsrun --stop'
alias ncsr='ncs --cd ~/ncsrun --reload'
alias sncs='source ~/nso-6.3.7/ncsrc'
# Git Pages check
alias gpc='docker run -e ANTORA_PLAYBOOK=local.yml -u $(id -u) -v "/$PWD:/antora:Z" --rm -it techdoc-docker-release-local.bahnhub.tech.rz.db.de/techdoc:2.3.2 build'
# SDE-NSO
alias mkb='make build'
alias mkc='make testenv-cli'
alias mkk='make testenv-stop'
alias mkl='make testenv-log-service'
alias mkr='make testenv-rebuild'
alias mks='make testenv-start'
alias mksh='make testenv-shell'
alias mkt='make testenv-test'
